name: CD - Deploy no GitHub Pages

on:
  workflow_run:
    workflows: ["CI - Validar e Testar"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Baixar artefato do CI
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ./dist

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v2
